# Generated by Django 6.0.2 on 2026-02-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femminicidioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='cognome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='utente',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
