# Generated by Django 6.0.1 on 2026-02-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femminicidioapp', '0002_alter_utente_cognome_alter_utente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='cell_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='utente',
            name='regione',
            field=models.CharField(blank=True, choices=['Abruzzo', 'Basilicata', 'Calabria', 'Campania', 'Emilia-Romagna', 'Friuli-Venezia Giulia', 'Lazio', 'Liguria', 'Lombardia', 'Marche', 'Molise', 'Piemonte', 'Puglia', 'Sardegna', 'Sicilia', 'Toscana', 'Trentino-Alto Adige', 'Umbria', "Valle d'Aosta", 'Veneto'], max_length=20, null=True),
        ),
    ]
