# Generated by Django 6.0.1 on 2026-02-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femminicidioapp', '0003_utente_cell_email_utente_regione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='regione',
            field=models.CharField(blank=True, choices=[('Abruzzo', 'Abruzzo'), ('Basilicata', 'Basilicata'), ('Calabria', 'Calabria'), ('Campania', 'Campania'), ('Emilia-Romagna', 'Emilia-Romagna'), ('Friuli-Venezia Giulia', 'Friuli-Venezia Giulia'), ('Lazio', 'Lazio'), ('Liguria', 'Liguria'), ('Lombardia', 'Lombardia'), ('Marche', 'Marche'), ('Molise', 'Molise'), ('Piemonte', 'Piemonte'), ('Puglia', 'Puglia'), ('Sardegna', 'Sardegna'), ('Sicilia', 'Sicilia'), ('Toscana', 'Toscana'), ('Trentino-Alto Adige', 'Trentino-Alto Adige'), ('Umbria', 'Umbria'), ("Valle d'Aosta", "Valle d'Aosta"), ('Veneto', 'Veneto')], max_length=20, null=True),
        ),
    ]
