# Generated by Django 6.0.1 on 2026-02-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femminicidioapp', '0004_alter_utente_regione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonianza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
