# Generated by Django 6.0.1 on 2026-02-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femminicidioapp', '0005_testimonianza'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonianza',
            name='utente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='testimonianze', to='femminicidioapp.utente'),
            preserve_default=False,
        ),
    ]
