# Generated by Django 6.0.1 on 2026-02-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femminicidioapp', '0006_testimonianza_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='cell_email',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utente',
            name='cognome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
