# Generated by Django 6.0.1 on 2026-02-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femminicidioapp', '0010_alter_testimonianza_stato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonianza',
            name='stato',
            field=models.CharField(choices=[('in_attesa', 'In attesa'), ('accettata', 'Accettata'), ('rifiutata', 'Rifiutata')], default='in_attesa', max_length=20),
        ),
    ]
